name: Dynamic Folder Index CI

on:
  push:
    # Only trigger this on master branch
    branches: [ master ]
    
    paths:
    # Only trigger this on changes to .rdfe files within the "Dynamic Folder" folder
    - "Dynamic Folder/**.rdfe"

  # Allow us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Rebuild Index Python Script
        working-directory: ./Dynamic Folder
        run: python3 rebuildindex.py
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          commit-message: "[ci] Dynamic Folder Index updated"
          title: "[ci] Dynamic Folder Index updated"
          body: "The Dynamic Folder Index was updated automatically by CI"
